version: '3.8'

services:
  reminder:
    build: 
      context: .
      dockerfile: Dockerfile
    healthcheck:
      timeout: 5s
    depends_on:
    - postgres

  postgres:
    image: postgres:latest     
    environment:
      POSTGRES_DB: reminder  
      POSTGRES_USER: reminder    
      POSTGRES_PASSWORD: password
